### ISSUE TITLE
corners of overlapping tiles

### ISSUE THREAD

**Issue by jo-pol** [d-bl/GroundForge#140]
[Patterns] with overlapping tiles have a problem in the prototype diagram. The symbol in the red circle of the screen shot should be bold. Now the stitch can't be changed. Until fixed, the green annotations show a work around: alter the default stitch in the address bar.

[Patterns]: https://d-bl.github.io/GroundForge/tiles?patchWidth=3&patchHeight=3&b1=ctc&c2=lctcl&a2=rctcr&b3=ctc&tile=831,4-7,158&tileStitch=ctctctctctc&shiftColsSW=-2&shiftRowsSW=2&shiftColsSE=2&shiftRowsSE=2

![afbeelding](https://user-images.githubusercontent.com/10553630/64913068-735b9400-d739-11e9-9c70-4b2940ec7bb0.png)

**Comment by MAETempels** [comment]
The corner left-under is also not bold. One of the two should be bold.
Seems like the initially bold symbol gets overwritten with not bold in the second itteration (j=1, j=-1).

Adding the bold attribute after the itterations solves the upper-right-corner, but will also put bold to the lower-left corner.
Could be hard to solve, since we do not know before-hand which is intended.
Not overwriting any symbol might also solve the problem, but leaves the bold lower-left.

I noticed:
Changing the lower-left corner to "-" leaves the pattern intact.
Changing upper-right to "-" ( and lower-left back to "1") distorts the pattern.
The same for the upper-left and lower-right corner.
I would expect in all cases: if there is already something there, do not overwrite.
